use_frameworks!

platform :ios, '8.0'

target 'TLFilterView_Example' do
  pod 'TLFilterView', :path => '../'

  target 'TLFilterView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
